name: rca-audit
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - conda-forge::openpyxl
  - matplotlib
  - conda-forge::jinja2
  - conda-forge::scipy
  - conda-forge::statsmodels
